### ISSUE TITLE
Link detecting inside main 

### ISSUE THREAD

**Issue by truthSeekr** [ncri/ajaxify_rails#16]
I want to make work ajaxify with links that appears in "changing content - class main". Can I refresh ajaxify in some way ? I was trying initialize Ajaxify again in content_inserted event but it was just unlucky shot.

**Comment by ncri** [comment]
Not sure what you mean? All links use Ajaxify by default.

**Comment by truthSeekr** [comment]
that was tottally different thing, my bad
links should start with "/" if not then my whole page is reloading ;/
